// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuiNamAnh0031.Migrations
{
    [DbContext(typeof(SQLite))]
    [Migration("20230623013657_tablecau1")]
    partial class tablecau1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BuiNamAnh0031.Models.BNALopHoc", b =>
                {
                    b.Property<string>("BNAMaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("BNATenLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BNAMaLop");

                    b.ToTable("BNALopHoc");
                });

            modelBuilder.Entity("BuiNamAnh0031.Models.BNASinhVien", b =>
                {
                    b.Property<string>("BNASinhVienMaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("BNAHoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BNAMaLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BNASinhVienMaSinhVien");

                    b.HasIndex("BNAMaLop");

                    b.ToTable("BNASinhVien");
                });

            modelBuilder.Entity("BuiNamAnh0031.Models.BNASinhVien", b =>
                {
                    b.HasOne("BuiNamAnh0031.Models.BNALopHoc", "BNALopHoc")
                        .WithMany()
                        .HasForeignKey("BNAMaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BNALopHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
